"use client";

import { useEffect, useState } from "react";
import Sidebar from "@/components/Sidebar";

const empty = { design: { primary_color: '#0f766e', font_family: 'Inter', content_width: '7xl', section_spacing: 'py-16' }, services: { enabled: true, heading: 'Other Services', description: '', contact_form_enabled: true, youtube_url: '', items: [] }, insurance: { enabled: true, heading: 'Travel Insurance', description: '', button_text: 'Enquire now', button_link: '/contact?subject=Travel%20Insurance' }, cookies: { enabled: true, message: 'We use cookies to improve your experience.', policy_url: '/privacy-policy', accept_text: 'Accept all', reject_text: 'Reject non-essential' }, crm: { provider: 'none', enabled: false, webhook_url: '', form_mapping: {} } };

function Field({ label, value, onChange, type = 'text', placeholder = '' }) { return <label className="block"><span className="admin-label">{label}</span>{type === 'textarea' ? <textarea value={value || ''} onChange={(e) => onChange(e.target.value)} className="admin-input" rows={3} placeholder={placeholder} /> : <input type={type} value={value || ''} onChange={(e) => onChange(e.target.value)} className="admin-input" placeholder={placeholder} />}</label>; }
function Toggle({ label, value, onChange }) { return <label className="flex items-center justify-between gap-4 p-3 rounded-lg bg-gray-50"><span className="font-medium text-sm">{label}</span><input type="checkbox" checked={Boolean(value)} onChange={(e) => onChange(e.target.checked)} className="h-4 w-4 accent-teal-600" /></label>; }

export default function SiteSettingsPage() {
  const [settings, setSettings] = useState(empty); const [message, setMessage] = useState(''); const [saving, setSaving] = useState('');
  useEffect(() => { fetch('/api/site-settings').then((r) => r.json()).then((d) => d.settings && setSettings((old) => ({ ...old, ...d.settings }))).catch(() => setMessage('Could not load saved settings.')); }, []);
  const update = (key, field, value) => setSettings((current) => ({ ...current, [key]: { ...current[key], [field]: value } }));
  const save = async (key) => { setSaving(key); setMessage(''); try { const r = await fetch('/api/site-settings', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ key, value: settings[key] }) }); if (!r.ok) throw new Error((await r.json()).error); setMessage(`${key.replace('_', ' ')} settings saved.`); } catch (e) { setMessage(e.message || 'Could not save settings.'); } finally { setSaving(''); } };
  const serviceItems = Array.isArray(settings.services.items) ? settings.services.items : [];
  return <div className="flex min-h-screen"><Sidebar /><main className="flex-1 p-8 overflow-y-auto"><div className="mb-6"><h1 className="text-2xl font-bold text-gray-900">Site Settings</h1><p className="text-gray-500 mt-1">Manage global styling, services, cookie consent, and CRM handoff.</p></div>{message && <div className="mb-6 rounded-lg bg-teal-50 p-3 text-sm text-teal-700">{message}</div>}
    <section className="admin-card mb-6"><h2 className="text-lg font-semibold mb-4">Global design</h2><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4"><Field label="Primary color" type="color" value={settings.design.primary_color} onChange={(v) => update('design','primary_color',v)} /><label><span className="admin-label">Font family</span><select value={settings.design.font_family} onChange={(e) => update('design','font_family',e.target.value)} className="admin-input"><option>Inter</option><option>DM Sans</option><option>Manrope</option><option>Playfair Display</option></select></label><label><span className="admin-label">Content width</span><select value={settings.design.content_width} onChange={(e) => update('design','content_width',e.target.value)} className="admin-input"><option value="7xl">7xl</option><option value="8xl">8xl</option><option value="9xl">9xl</option></select></label><label><span className="admin-label">Section spacing</span><select value={settings.design.section_spacing} onChange={(e) => update('design','section_spacing',e.target.value)} className="admin-input"><option value="py-12">Compact</option><option value="py-16">Regular</option><option value="py-24">Spacious</option></select></label></div><button onClick={() => save('design')} className="admin-btn mt-4" disabled={saving === 'design'}>Save design settings</button></section>
    <section className="admin-card mb-6"><h2 className="text-lg font-semibold mb-4">Other services & contact form</h2><div className="grid gap-4 md:grid-cols-2"><Field label="Section heading" value={settings.services.heading} onChange={(v) => update('services','heading',v)} /><Field label="YouTube button URL" value={settings.services.youtube_url} onChange={(v) => update('services','youtube_url',v)} placeholder="https://youtube.com/..." /><div className="md:col-span-2"><Field label="Description" type="textarea" value={settings.services.description} onChange={(v) => update('services','description',v)} /></div><Toggle label="Show Other Services section" value={settings.services.enabled} onChange={(v) => update('services','enabled',v)} /><Toggle label="Enable user contact/enquiry form" value={settings.services.contact_form_enabled} onChange={(v) => update('services','contact_form_enabled',v)} /></div><div className="mt-4"><p className="admin-label">Service cards</p>{serviceItems.map((item, index) => <div className="flex gap-2 mb-2" key={index}><input className="admin-input" value={item} onChange={(e) => update('services','items',serviceItems.map((value,i) => i === index ? e.target.value : value))} /><button onClick={() => update('services','items',serviceItems.filter((_,i) => i !== index))} className="admin-btn-danger px-3">Remove</button></div>)}<button onClick={() => update('services','items',[...serviceItems, ''])} className="admin-btn-secondary mt-1">Add service</button></div><button onClick={() => save('services')} className="admin-btn mt-4" disabled={saving === 'services'}>Save services</button></section>
    <section className="admin-card mb-6"><h2 className="text-lg font-semibold mb-4">Travel insurance</h2><div className="grid gap-4 md:grid-cols-2"><Field label="Heading" value={settings.insurance.heading} onChange={(v) => update('insurance','heading',v)} /><Field label="Button text" value={settings.insurance.button_text} onChange={(v) => update('insurance','button_text',v)} /><div className="md:col-span-2"><Field label="Description" type="textarea" value={settings.insurance.description} onChange={(v) => update('insurance','description',v)} /></div><Field label="Button link" value={settings.insurance.button_link} onChange={(v) => update('insurance','button_link',v)} /><Toggle label="Show Travel Insurance section" value={settings.insurance.enabled} onChange={(v) => update('insurance','enabled',v)} /></div><button onClick={() => save('insurance')} className="admin-btn mt-4" disabled={saving === 'insurance'}>Save insurance</button></section>
    <section className="admin-card mb-6"><h2 className="text-lg font-semibold mb-4">Cookie consent</h2><div className="grid gap-4 md:grid-cols-2"><div className="md:col-span-2"><Field label="Consent message" type="textarea" value={settings.cookies.message} onChange={(v) => update('cookies','message',v)} /></div><Field label="Privacy policy URL" value={settings.cookies.policy_url} onChange={(v) => update('cookies','policy_url',v)} /><Field label="Accept button" value={settings.cookies.accept_text} onChange={(v) => update('cookies','accept_text',v)} /><Field label="Reject button" value={settings.cookies.reject_text} onChange={(v) => update('cookies','reject_text',v)} /><Toggle label="Show cookie consent banner" value={settings.cookies.enabled} onChange={(v) => update('cookies','enabled',v)} /></div><button onClick={() => save('cookies')} className="admin-btn mt-4" disabled={saving === 'cookies'}>Save cookie settings</button></section>
    <section className="admin-card"><h2 className="text-lg font-semibold mb-1">CRM integration</h2><p className="text-sm text-gray-500 mb-4">Use a secure server-side webhook URL from your CRM provider; never enter secret API keys here.</p><div className="grid gap-4 md:grid-cols-2"><label><span className="admin-label">CRM provider</span><select value={settings.crm.provider} onChange={(e) => update('crm','provider',e.target.value)} className="admin-input"><option value="none">Not connected</option><option value="hubspot">HubSpot</option><option value="zoho">Zoho</option><option value="salesforce">Salesforce</option><option value="webhook">Custom webhook</option></select></label><Field label="Secure webhook URL" value={settings.crm.webhook_url} onChange={(v) => update('crm','webhook_url',v)} placeholder="https://..." /><Toggle label="Enable CRM form handoff" value={settings.crm.enabled} onChange={(v) => update('crm','enabled',v)} /></div><button onClick={() => save('crm')} className="admin-btn mt-4" disabled={saving === 'crm'}>Save CRM configuration</button></section>
  </main></div>;
}
